import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import QueryClientProvider from "./QueryClientProvider";
import AuthProvider from "./auth/Provider";
import "./globals.css";
import "./theme-config.css";
import {
  NextIntlClientProvider,
  useMessages,
  useTranslations,
} from "next-intl";
import { useTranslate } from "@/app/Translations";
import { link } from "fs";
import { Status } from "@prisma/client";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const translations = {
    links: [
      {
        label: useTranslate("components.navBar.links.dashboard"),
        href: "/dashbord",
        startLink: "/dashbord",
      },
      {
        label: useTranslate("components.navBar.links.thesis"),
        href: "/thesis/list",
        startLink: "/thesis",
      },
      {
        label: useTranslate("components.navBar.links.students"),
        href: "/students/list",
        startLink: "/students",
      },
    ],
    action: useTranslate("components.navBar.action"),
    logout: useTranslate("components.navBar.logout")
  };

  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.variable}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <QueryClientProvider>
            <Theme appearance="light" accentColor="blue" radius="large">
              <AuthProvider>
                <NavBar translations={translations} />
                <main className="p-5">
                  <Container>{children}</Container>
                </main>
              </AuthProvider>
            </Theme>
          </QueryClientProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
